### ISSUE TITLE
Laf not opening on linux.

### ISSUE THREAD

**Issue by zozonteq** [Hiro527/LaF#43]
Log
```
$ ./LaF_Setup_Linux_x86_64.AppImage 
21:23:36.445 › LaF v6.0.4
    - electron@10.4.7
    - nodejs@12.16.3
    - Chromium@85.0.4183.121
21:23:36.451 › Script Loaded: js/util/settings.js
21:23:36.452 › Script Loaded: js/util/wm.js
21:23:36.453 › UI Language: undefined
21:23:36.454 › Chromium Options:
    - disable-frame-rate-limit, null: Enable
    - disable-gpu-vsync, null: Enable
    - use-angle, default: Enable
    - enable-webgl2-compute-context, null: Enable
    - disable-accelerated-2d-canvas, true: Disable
    - in-process-gpu, null: Disable
    - autoplay-policy, no-user-gesture-required: Enable
21:23:36.686 › Discord Login OK
(node:8290) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/tmp/.mount_LaF_SeaSq2cp/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:417:26)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:8290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[8290:0617/212337.881410:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
$ 
```
## Enviroment
OS:Arch_Linux_x86
DE:GNOME 42
GPU:RTX 3090
NVIDIA Driver Version:515.48.07
Display Server:X11
##  Workaround
You can use the --no-sandbox option to launch the program successfully.
```
$ ./LaF_Setup_Linux_x86_64.AppImage --no-sandbox
```

**Comment by asger-finding** [comment]
All krunker clients with electron 9 have this issue. However, it isn't a problem with all distros. The `disable-gpu-sandbox` flag should also work.

**Comment by zozonteq** [comment]
When I built it from the source code, it started without "--no-sandbox". This issue may be resolved in the next release.
